server.port: 8902

spring:
  aop:
    auto: true
  application:
    version: v1
    cnname: dbus控制台-v1
    name: dbus-keeper-mgr-${spring.application.version}
  messages:
    encoding: UTF-8
    cache-seconds: 3600
    basename: i18n/messages
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
management.security.enabled: false

eureka:
  instance:
    metadataMap.alarmEmail: bridata@126.com
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl.defaultZone: http://dbus-n1:9090/eureka/
zk:
  str: dbus-n1:2181

pubKeyPath: ~/.ssh/id_rsa