server.port: #{gateway.server.port}#
spring.application.name: dbus-keeper-gateway
token.sign.key: token.2018.03.23
token.expire.minutes: 600000000

spring:
  messages:
    cache-seconds: 3600
    encoding: UTF-8
    basename: i18n/messages
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
eureka:
  instance:
    metadataMap.alarmEmail: #{eureka.instance.metadataMap.alarmEmail}#
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl.defaultZone: #{eureka.client.serviceUrl.defaultZone}#

zuul:
  ignoredPatterns: /**/login
  routes:
    keeper-mgr:
      path: /v1/keeper/**
      serviceId: dbus-keeper-mgr-v1
  sensitive-headers:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
