server.port: 10001
spring:
  application:
    version: v1
    cnname: dbus-keeper服务-v1
    name: dbus-keeper-service-${spring.application.version}
  datasource:
    password: HxP31vevLw9PoiT/
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dbus-n1:3306/dbusmgr?characterEncoding=utf-8
    username: dbusmgr
  messages:
    cache-seconds: 3600
    encoding: UTF-8
    basename: i18n/messages
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.creditease.domain.model

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management.security.enabled: false

eureka:
  instance:
    metadataMap.alarmEmail: bridata@126.com
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl.defaultZone: http://dbus-n1:9090/eureka/

zk:
  str: dbus-n1:2181