server.port: 9091
spring.application.name: config-server

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181/kafka
    config.server.git:
      uri: https://github.com/yourname/yourproject
      searchPaths: '*'  #搜索各个以服务名命名的文件夹下的所有yml
      label: master
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:9090/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true

management:
  security:
    enabled: false